[package]
name = "kylaaa/twitchblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["Src", "Packages", "default.project.json"]

[dependencies]
Freeze = "duckarmor/freeze@0.0.2"
Http = "kylaaa/http@0.2.0"
Karen = "kylaaa/karen@0.1.2"
Promise = "evaera/promise@4.0.0"
Rodux = "roblox/rodux@4.0.0"
Signal = "sleitnick/signal@1.3.0"