[package]
name = "kylaaa/twitchblox"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["Src", "default.project.json"]
exclude = ["Bin", "Build", "Debug", "Packages", "standalone.project.json", "test.project.json"]

[dependencies]
Http = "kylaaa/http@0.5.0"
Karen = "kylaaa/karen@0.1.3"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.3.0"